[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "fitz>=0.0.1.dev2",
    "kivy>=2.3.1",
    "pymupdf==1.25.0",
]
