name: Build Kivy App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Updated to latest version
    
    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to latest version
      with:
        python-version: "3.10"  # Use latest stable version compatible with Kivy
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev build-essential zlib1g-dev liblzma-dev openjdk-17-jdk
        python -m pip install --upgrade pip
        pip install buildozer cython pillow plyer

    - name: Set up Android SDK
      run: |
        # Install SDK tools
        echo "Setting up Android SDK..."
        mkdir -p $HOME/android-sdk
        cd $HOME/android-sdk
        
        # Download and extract the command-line tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
        unzip commandlinetools-linux-7302050_latest.zip
        
        # Move the tools into the correct directory
        mv cmdline-tools $HOME/android-sdk/cmdline-tools
        
        # Accept SDK licenses
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        
        # Install required Android SDK components
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --install "build-tools;34.0.0" "platform-tools" "platforms;android-34"
        
        # Set ANDROID_HOME environment variable
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH

    - name: Build Kivy app using Buildozer
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init  # Only initialize if the file does not exist
        fi
        # Build the APK
        buildozer -v android debug  # Change to "release" if needed
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4  # ✅ Updated to v4
      with:
        name: android-debug-apk
        path: bin/*.apk
