name: Build Kivy Android App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y openjdk-8-jdk unzip wget
        python -m pip install --upgrade pip
        pip install kivy buildozer cython

    - name: Install Android SDK
      run: |
        mkdir -p $HOME/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O commandlinetools.zip
        unzip -q commandlinetools.zip -d $HOME/android-sdk
        mv $HOME/android-sdk/cmdline-tools $HOME/android-sdk/latest
        mkdir -p $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/latest $HOME/android-sdk/cmdline-tools/latest

        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH

        yes | sdkmanager --licenses
        yes | sdkmanager --sdk_root=$ANDROID_HOME --update
        yes | sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "build-tools;33.0.2" "platforms;android-33" "ndk;25.2.9519653"

    - name: Build Android app with Buildozer
      run: |
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        buildozer android debug

    - name: Upload APK to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: ./bin/*.apk
