name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools python3-dev build-essential git
          sudo apt-get install -y libssl-dev libffi-dev python3-venv libncurses5-dev libstdc++6 libsqlite3-dev zlib1g-dev liblzma-dev

      # Install Buildozer
      - name: Install Buildozer
        run: |
          pip install buildozer

      # Build the APK
      - name: Build APK
        run: |
          cd /path/to/your/project
          buildozer -v android debug

      # Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: kivy-apk
          path: bin/*.apk
