name: Android Build Tools Setup with Buildozer

on:
  push:
    branches:
      - main

jobs:
  setup-build-tools-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Android SDK
      run: |
        # Set up Android SDK path
        export ANDROID_HOME=$HOME/android-sdk
        export ANDROID_SDK_ROOT=$ANDROID_HOME
        mkdir -p $ANDROID_HOME/cmdline-tools/latest

        # Download command-line tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O commandlinetools.zip
        unzip -q commandlinetools.zip -d $ANDROID_HOME/cmdline-tools
        mv $ANDROID_HOME/cmdline-tools/cmdline-tools/* $ANDROID_HOME/cmdline-tools/latest/

        # Ensure sdkmanager is executable
        chmod +x $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager

        # Update SDK manager to get latest package list
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --update

        # Accept licenses automatically
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

        # Install required build-tools versions
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;30.0.3" "build-tools;29.0.2" "build-tools;28.0.3"
        # Install additional required SDK components
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-30" "platform-tools"

    - name: Install Dependencies
      run: |
        # Update and install Buildozer dependencies
        sudo apt update
        sudo apt install -y python3-pip python3-dev build-essential libssl-dev libffi-dev python3-setuptools
        sudo apt install -y git
        pip3 install --upgrade pip

    - name: Install Buildozer
      run: |
        # Install Buildozer and other required tools
        pip3 install buildozer

    - name: Build with Buildozer
      run: |
        # Build the Android app with Buildozer
        buildozer android debug
