name: Android Build Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Android SDK
      uses: reactivecircus/android-sdk-update-activity@v2
      with:
        api-level: 30
        build-tools: 30.0.3
        ndk-version: 21.3.6528147

    - name: Install Build-Tools and checking AIDL...
      run: |
        echo "Installing Build-Tools and checking AIDL..."
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;30.0.3" "build-tools;29.0.2"
        
        # Check if AIDL is installed
        if [ -f "$ANDROID_HOME/build-tools/30.0.3/aidl" ]; then
          echo "AIDL is available in Build-Tools 30.0.3"
        else
          echo "AIDL not found in Build-Tools 30.0.3, checking other versions"
        fi
        
        # Try another version of build-tools if AIDL is not found
        if [ ! -f "$ANDROID_HOME/build-tools/30.0.3/aidl" ]; then
          echo "Trying build-tools 29.0.2..."
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;29.0.2"
        fi

        # Check if AIDL is available now
        if [ -f "$ANDROID_HOME/build-tools/29.0.2/aidl" ]; then
          echo "AIDL is available in Build-Tools 29.0.2"
        else
          echo "AIDL is still not available."
          exit 1
        fi

        # Add build-tools directory to PATH
        echo "Adding build-tools directory to PATH..."
        echo "$ANDROID_HOME/build-tools/30.0.3" >> $GITHUB_ENV
        echo "PATH=$PATH:$ANDROID_HOME/build-tools/30.0.3" >> $GITHUB_ENV

    - name: Check AIDL availability
      run: |
        echo "Checking AIDL tool..."
        if command -v aidl; then
          echo "AIDL command is available."
        else
          echo "AIDL command is NOT available."
          exit 1
          
    - name: Build the app
      run: |
        # Add your build commands here
        echo "Building the app..."

    - name: Run tests
      run: |
        # Add your testing commands here
        echo "Running tests..."

