name: Build Android App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up the Android SDK
      - name: Set up Android SDK
        run: |
          # Download and unzip command-line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O commandlinetools.zip
          unzip -q commandlinetools.zip -d $HOME/android-sdk

          # Move the unzipped folder to the expected location
          mv $HOME/android-sdk/cmdline-tools-linux $HOME/android-sdk/cmdline-tools

          # Set up environment variables for SDK
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/30.0.3" >> $GITHUB_ENV

      # Install Android Build tools and accept licenses
      - name: Install Android Build-Tools
        run: |
          # Install SDK Manager and accept licenses
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --update
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;30.0.3" "platform-tools" --verbose

      # Verify Build Tools installation
      - name: Verify Build Tools installation
        run: |
          ls -l $ANDROID_HOME/build-tools

      # Set up Python environment and dependencies for buildozer
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Install Buildozer
      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer

      # Build the app with Buildozer
      - name: Build the app with Buildozer
        run: |
          buildozer android debug
          
      # Cache Android SDK to speed up subsequent builds
      - name: Cache Android SDK
        uses: actions/cache@v2
        with:
          path: $HOME/android-sdk
          key: ${{ runner.os }}-android-sdk-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-android-sdk-
