name: Build Kivy Android App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Clear Python cache
    - name: Clear Python cache
      run: |
        rm -rf $HOME/.cache/pip
        rm -rf $HOME/.cache/actions/setup-python

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'   # Ensuring we're using 3.10

    - name: Check Python version
      run: |
        python --version

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y openjdk-8-jdk unzip wget
        python -m pip install --upgrade pip
        pip install kivy buildozer

    - name: Install Android SDK
      run: |
        mkdir -p $HOME/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O commandlinetools.zip
        unzip commandlinetools.zip -d $HOME/android-sdk
        yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk --update
        yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "build-tools;30.0.3" "android-30"

    - name: Build Android app with Buildozer
      run: |
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools:$PATH
        buildozer android debug

    - name: Upload APK to GitHub (optional)
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: ./bin/*.apk
