name: Android SDK Setup, AIDL Check, and APK Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-android-sdk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip openjdk-8-jdk

    - name: Create necessary directories for Android SDK
      run: |
        mkdir -p /home/runner/android-sdk/cmdline-tools
        mkdir -p /home/runner/android-sdk/platform-tools

    - name: Download Android SDK Command-Line Tools
      run: |
        # Download a known version of the SDK command-line tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
        
        # Check if the download succeeded
        if [ $? -ne 0 ]; then
          echo "Download failed!"
          exit 1
        fi

        # Unzip the file into the correct directory
        unzip cmdline-tools.zip -d /home/runner/android-sdk/cmdline-tools

    - name: List SDK directory for debugging
      run: |
        # List the contents of the extracted SDK to verify sdkmanager location
        ls -R /home/runner/android-sdk/cmdline-tools/

    - name: Set environment variables for SDK
      run: |
        # Set environment variables for the SDK
        echo "ANDROID_HOME=/home/runner/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=/home/runner/android-sdk" >> $GITHUB_ENV
        echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
        echo "PATH=$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

    - name: Verify sdkmanager installation
      run: |
        # Check if sdkmanager exists directly at the expected location
        if [ -f "/home/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager" ]; then
          echo "sdkmanager found at /home/runner/android-sdk/cmdline-tools/latest/bin/"
        else
          echo "sdkmanager not found in the expected location."
          exit 1
        fi

    - name: Install SDK components (including AIDL)
      run: |
        # If sdkmanager is found, proceed to install SDK components
        if [ -f "/home/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager" ]; then
          yes | /home/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager --update
          yes | /home/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager "platforms;android-30"
          yes | /home/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager "build-tools;30.0.3"
          yes | /home/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager "cmdline-tools;latest"
          yes | /home/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager "tools"
          yes | /home/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager "extras;android;m2repository"
          yes | /home/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager "extras;google;m2repository"
        else
          echo "sdkmanager not found in the expected location. Exiting."
          exit 1
        fi

    - name: Check if AIDL is installed
      run: |
        # Verify if AIDL tool is available
        if command -v aidl > /dev/null 2>&1; then
          echo "AIDL tool is installed."
        else
          echo "AIDL tool is not found."
          exit 1
        fi

  build-apk:
    runs-on: ubuntu-latest
    needs: setup-android-sdk

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        pip install --upgrade pip
        pip install buildozer

    - name: Install required Android dependencies
      run: |
        yes | sdkmanager "platforms;android-30"
        yes | sdkmanager "build-tools;30.0.3"

    - name: Build APK with Buildozer
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: apk-artifact
        path: ./bin/*.apk

  # Optional: Clean up
  clean-up:
    runs-on: ubuntu-latest
    needs: build-apk

    steps:
    - name: Clean up
      run: |
        rm -rf ./bin
