name: Android SDK Setup, AIDL Check, and APK Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-android-sdk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 30
        build-tools: 30.0.3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip openjdk-8-jdk

    - name: Install SDK components (including AIDL)
      run: |
        # Update SDK manager
        yes | sdkmanager --update
        # Install platform tools, build tools, cmdline-tools (which include AIDL)
        yes | sdkmanager "platforms;android-30"
        yes | sdkmanager "build-tools;30.0.3"
        yes | sdkmanager "cmdline-tools;latest"
        
    - name: Check if AIDL is installed
      run: |
        # Verify if AIDL tool is available
        if command -v aidl > /dev/null 2>&1; then
          echo "AIDL tool is installed."
        else
          echo "AIDL tool is not found."
          exit 1
        fi

  build-apk:
    runs-on: ubuntu-latest
    needs: setup-android-sdk

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        pip install --upgrade pip
        pip install buildozer

    - name: Install required Android dependencies
      run: |
        # Ensure the required SDK components are installed again
        yes | sdkmanager "platforms;android-30"
        yes | sdkmanager "build-tools;30.0.3"

    - name: Build APK with Buildozer
      run: |
        buildozer android debug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: apk-artifact
        path: ./bin/*.apk

  # Optional: Clean up
  clean-up:
    runs-on: ubuntu-latest
    needs: build-apk

    steps:
    - name: Clean up
      run: |
        rm -rf ./bin
