name: Android Build Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Android SDK and Build-Tools
      run: |
        echo "Installing Android SDK and Build-Tools..."
        sudo apt-get update
        sudo apt-get install -y wget unzip
        # Download and install Android SDK Command Line Tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
        unzip commandlinetools-linux-6858069_latest.zip -d $HOME/android-sdk
        rm commandlinetools-linux-6858069_latest.zip
        
        # Add Android SDK to PATH
        echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV
        
        # Install Build Tools and other SDK components
        yes | sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "build-tools;30.0.3" "build-tools;29.0.2" "platforms;android-30"
        
        # Install AIDL tools if available
        echo "Checking AIDL availability..."
        if [ -f "$ANDROID_HOME/build-tools/30.0.3/aidl" ]; then
          echo "AIDL is available in Build-Tools 30.0.3"
        else
          echo "AIDL not found in Build-Tools 30.0.3, checking other versions"
        fi

        # If AIDL isn't found, try the other version
        if [ ! -f "$ANDROID_HOME/build-tools/30.0.3/aidl" ]; then
          echo "Trying build-tools 29.0.2..."
          yes | sdkmanager --sdk_root=$ANDROID_HOME "build-tools;29.0.2"
        fi

        # Check if AIDL is now available
        if [ -f "$ANDROID_HOME/build-tools/29.0.2/aidl" ]; then
          echo "AIDL is available in Build-Tools 29.0.2"
        else
          echo "AIDL is still not available."
          exit 1
        fi

    - name: Check AIDL tool
      run: |
        echo "Checking AIDL tool..."
        if command -v aidl; then
          echo "AIDL command is available."
        else
          echo "AIDL command is NOT available."
          exit 1

    - name: Build the app
      run: |
        # Add your build commands here
        echo "Building the app..."

    - name: Run tests
      run: |
        # Add your testing commands here
        echo "Running tests..."
