name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools python3-dev build-essential git
          sudo apt-get install -y libssl-dev libffi-dev python3-venv libncurses5-dev libstdc++6 libsqlite3-dev zlib1g-dev liblzma-dev
          sudo apt-get install -y python3-pyqt5 python3-scipy

      # Install Cython
      - name: Install Cython
        run: |
          pip install cython

      # Install Buildozer
      - name: Install Buildozer
        run: |
          pip install buildozer

      # Install Android SDK and Build Tools
      - name: Install Android SDK and Build Tools
        run: |
          # Create the necessary directory for the SDK
          mkdir -p $HOME/Android/Sdk

          # Install Android SDK Command Line Tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-7583922_latest.zip -d $HOME/Android/Sdk

          # Create 'latest' folder and move contents into it
          mkdir -p $HOME/Android/Sdk/cmdline-tools/latest
          mv $HOME/Android/Sdk/cmdline-tools/* $HOME/Android/Sdk/cmdline-tools/latest/

          # Accept SDK licenses and install required tools
          echo "y" | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;36.0.0" "platforms;android-30"

      # Build the APK
      - name: Build APK
        run: |
          cd $GITHUB_WORKSPACE  # Ensure we are in the correct directory
          buildozer -v android debug

      # Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk
