name: Build Kivy App with Buildozer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java JDK 8
        run: sudo apt install -y openjdk-8-jdk

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y \
            unzip \
            wget \
            curl \
            git \
            python3 \
            python3-pip \
            python3-dev \
            build-essential \
            libssl-dev \
            libffi-dev \
            libmysqlclient-dev

      - name: Install Android SDK
        run: |
          mkdir -p /home/runner/android-sdk/cmdline-tools && \
          cd /home/runner/android-sdk/cmdline-tools && \
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip && \
          unzip commandlinetools-linux-7583922_latest.zip && \
          rm commandlinetools-linux-7583922_latest.zip && \
          mv cmdline-tools /home/runner/android-sdk/cmdline-tools/latest

      - name: Verify SDK Manager
        run: |
          ls -l /home/runner/android-sdk/cmdline-tools/latest/

      - name: Accept Android SDK licenses
        run: |
          chmod +x /home/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager && \
          yes | /home/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install Android SDK components
        run: |
          /home/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"

      - name: Install Python packages
        run: pip3 install kivy buildozer

      - name: Run Buildozer to build the app
        run: buildozer android debug
