name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools python3-dev build-essential git
          sudo apt-get install -y libssl-dev libffi-dev python3-venv libncurses5-dev libstdc++6 libsqlite3-dev zlib1g-dev liblzma-dev
          sudo apt-get install -y python3-pyqt5 python3-scipy

      # Install Cython
      - name: Install Cython
        run: |
          pip install cython

      # Install Buildozer
      - name: Install Buildozer
        run: |
          pip install buildozer

      # Install Android SDK Command Line Tools
      - name: Install Android SDK Command Line Tools
        run: |
          # Create necessary directory for Android SDK
          mkdir -p $HOME/Android/Sdk

          # Download command line tools zip
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip

          # Unzip the command line tools into the correct directory
          unzip commandlinetools-linux-7583922_latest.zip -d $HOME/Android/Sdk/

          # Move cmdline-tools to a specific folder structure
          mv $HOME/Android/Sdk/cmdline-tools $HOME/Android/Sdk/cmdline-tools-temp
          mkdir -p $HOME/Android/Sdk/cmdline-tools/latest
          mv $HOME/Android/Sdk/cmdline-tools-temp/* $HOME/Android/Sdk/cmdline-tools/latest/

          # Accept all licenses explicitly with yes command
          yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --licenses

          # Install required packages explicitly
          yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30" "extras;google;m2repository" "extras;android;m2repository" "tools" "ndk;21.3.6528147" "system-images;android-30;google_apis;x86_64"

      # Check if Android SDK build-tools are present
      - name: Check Android SDK Build-Tools directory
        run: |
          # List the SDK directory to confirm if build-tools exist
          if [ -d "$HOME/Android/Sdk/build-tools" ]; then
            echo "Build-tools directory exists:"
            ls -alh $HOME/Android/Sdk/build-tools/
          else
            echo "Build-tools directory not found!"
          fi

      # Build the APK
      - name: Build APK
        run: |
          cd $GITHUB_WORKSPACE  # Ensure we are in the correct directory
          buildozer -v android debug

      # Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk
