name: Build Kivy Android App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y openjdk-8-jdk unzip wget
        python -m pip install --upgrade pip
        pip install kivy buildozer cython

    - name: Install Android SDK
      run: |
        # Set up SDK directories
        export ANDROID_HOME=$HOME/android-sdk
        export ANDROID_SDK_ROOT=$ANDROID_HOME
        mkdir -p $ANDROID_HOME/cmdline-tools/latest

        # Download and extract command-line tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O commandlinetools.zip
        unzip -q commandlinetools.zip -d $ANDROID_HOME/cmdline-tools
        if [ -d "$ANDROID_HOME/cmdline-tools/cmdline-tools" ]; then
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools/* $ANDROID_HOME/cmdline-tools/latest/
        fi

        # Ensure sdkmanager is executable
        chmod +x $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager

        # Export paths for Android SDK
        echo "export ANDROID_HOME=$HOME/android-sdk" >> ~/.bashrc
        echo "export ANDROID_SDK_ROOT=$ANDROID_HOME" >> ~/.bashrc
        echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> ~/.bashrc
        source ~/.bashrc

        # Ensure sdkmanager has the latest list of packages
        echo "Updating SDK package list..."
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --update

        # Accept all SDK licenses automatically with non-interactive prompt
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

        # List available SDK packages and check for build-tools versions
        echo "Listing available SDK packages..."
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list

        # Check if build-tools versions are available
        echo "Checking for available build-tools versions..."
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list | grep "build-tools"

        # Attempt installing specific build-tools versions
        echo "Attempting to install build-tools 30.0.3, 29.0.2, and 28.0.3..."
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --verbose "build-tools;30.0.3" "build-tools;29.0.2" "build-tools;28.0.3" "platform-tools" "platforms;android-34" "ndk;25.2.9519653"

    - name: Verify Build-Tools Installation
      run: |
        # Check if the correct Build-tools versions are installed
        if [ ! -d "$ANDROID_HOME/build-tools/30.0.3" ] && [ ! -d "$ANDROID_HOME/build-tools/29.0.2" ] && [ ! -d "$ANDROID_HOME/build-tools/28.0.3" ]; then
          echo "Error: Required Android Build-Tools not installed!"
          exit 1
        fi
        echo "Required Build-tools installed successfully"

    - name: Build Android app with Buildozer
      run: |
        export ANDROID_HOME=$HOME/android-sdk
        export ANDROID_SDK_ROOT=$ANDROID_HOME
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        source ~/.bashrc

        # Verify sdkmanager works
        sdkmanager --version || { echo "Error: sdkmanager not found!"; exit 1; }

        # Build APK
        buildozer android debug

    - name: Upload APK to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: ./bin/*.apk
