name: Build APK with Buildozer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Or the version required by your Kivy project

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev
        sudo apt-get install -y libjpeg-dev zlib1g-dev
        sudo apt-get install -y git
        sudo apt-get install -y liblzma-dev
        sudo apt-get install -y libmysqlclient-dev

        # Install Kivy and Buildozer
        pip install kivy buildozer

    - name: Install Android dependencies (optional if you need android SDK)
      run: |
        sudo apt-get install -y openjdk-8-jdk
        yes | sdkmanager --update
        yes | sdkmanager "platforms;android-30"
        yes | sdkmanager "build-tools;30.0.3"
        yes | sdkmanager "cmdline-tools;latest"

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: apk
        path: bin/*.apk
